version: '3.8'
services:
  fe:
    container_name: themesong-client
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - themesong-network
networks:
  themesong-network:
    external: true
