name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.PI_HOST}}
          username: ${{secrets.PI_USERNAME}}
          key: ${{secrets.PI_KEY}}
          script: |
            cd ${{github.event.repository.name}}
            git pull origin main
            sudo make rebuild
